#!/bin/sh

export LD_LIBRARY_PATH=/out/lib
exec /usr/local/bin/rtorrent \
		-o import=/config/.rtorrent.rc \
		-o port_range=10001-10001 \
		-o scgi_port=127.0.0.1:5000 \
		-o system.daemon.set=true \
		-o session=/session
